### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by HelenaLisenok** [HelenaLisenok/Homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by PawelPavlovich** [comment]
Donald John Trump was born on June 14, 1946, at Jamaica Hospital in the borough of Queens in New York City, the fourth child of Fred Trump, a Bronx-born real estate developer whose parents were German immigrants, and Mary Anne MacLeod Trump, an immigrant from Scotland. Trump grew up with older siblings Maryanne, Fred Jr., and Elizabeth, and younger brother Robert in the Jamaica Estates neighborhood of Queens and attended the private Kew-Forest School from kindergarten through seventh grade. At age 13, he was enrolled in the New York Military Academy, a private boarding school,and in 1964, he enrolled at Fordham University. Two years later he transferred to the Wharton School of the University of Pennsylvania, graduating in May 1968 with a B.S. in economics.In 2015, Trump's lawyer Michael Cohen threatened Fordham University and the New York Military Academy with legal action if they released Trump's academic records While in college, Trump obtained four student draft deferments. In 1966, he was deemed fit for military service based upon a medical examination, and in July 1968 a local draft board classified him as eligible to serve. In October 1968, he was classified 1-Y, a conditional medical deferment, and in 1972, he was reclassified 4-F due to bone spurs, permanently disqualifying him from service.

While a student at Wharton and after graduating in 1968, Trump worked at his father Fred's real estate company, Trump Management, which owned middle-class rental housing in New York City's outer boroughs.In 1971, he became president of the company and began using The Trump Organization as an umbrella brand. It was registered as a corporation in 1981.
Trump attracted public attention in 1978 with the launch of his family's first Manhattan venture, the renovation of the derelict Commodore Hotel, adjacent to Grand Central Terminal. The financing was facilitated by a $400 million city property tax abatement arranged by Fred Trump who also joined Hyatt in guaranteeing $70 million in bank construction financing.
In 1988, Trump acquired the Plaza Hotel in Manhattan with a loan of $425 million from a consortium of banks. Two years later, the hotel filed for bankruptcy protection, and a reorganization plan was approved in 1992
In 1985, Trump acquired the Mar-a-Lago estate in Palm Beach, Florida Trump converted the estate into a private club with an initiation fee and annual dues and used a wing of the house as a private residence. In 2019, Trump declared Mar-a-Lago his primary residence] although under a 1993 agreement with the Town of Palm Beach, Trump may spend no more than three weeks per year there.
In 2004, Trump co-founded Trump University, a company that sold real estate training courses priced from $1,500 to $35,000. After New York State authorities notified the company that its use of the word "university" violated state law, its name was changed to Trump Entrepreneur Initiative in 2010.
In 2013, the State of New York filed a $40 million civil suit against Trump University, alleging that the company made false statements and defrauded consumers. In addition, two class actions were filed in federal court against Trump and his companies.
Trump ran in the California and Michigan primaries for nomination as the Reform Party candidate for the 2000 presidential election but withdrew from the race in February 2000. A July 1999 poll matching him against likely Republican nominee George W. Bush and likely Democratic nominee Al Gore showed Trump with seven percent support.
On June 16, 2015, Trump announced his candidacy for President of the United States.His campaign was initially not taken seriously by political analysts, but he quickly rose to the top of opinion polls
On November 8, 2016, Trump received 306 pledged electoral votes versus 232 for Clinton. The official counts were 304 and 227 respectively, after defections on both sides. Trump received nearly 2.9 million fewer popular votes than Clinton, which made him the fifth person to be elected president while losing the popular vote

**Comment by HelenaLisenok** [comment]
I think he is an interesting person
