### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by HelenaLisenok** [HelenaLisenok/Homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by PawelPavlovich** [comment]
Interesting facts about Donald Trump

**Comment by PawelPavlovich** [comment]
Interesting facts about Donald Trump
1. Donald Trump was sent to Military School for Bad Behavior in his teen years.
2. 2. He’s a Germaphobe who does not like to shake hands.
3. Trump Management Corporation was once sued by The Department of Justice for discrimination because they would not rent to people of a certain race.
4. In 1990, Donald Trump won a Razzie for Worst Supporting Actor for his role in Ghost Can’t Do It.
5. 5. Trump sued Bill Maher for calling his father a monkey.
6. Trump doesn’t drink alcohol. His brother was an alcoholic and died because of his addiction in 1982.
7. SPY Magazine once sent some of the world’s richest people checks of 13 cents to see who would cash them. The only people to do so were an arms dealer and Donald Trump.
8. 8. Trump has run for president before. He won the California presidential primary for the Reform Party in 2000.
9. He passed up the chance to buy the New England Patriots back in the 80s because he thought they were a bad investment.
10. Trump owned 14,000 apartments by the time he was 27.
11. 11. Donald Trump Hit it Big with the Television Show “The Apprentice” and was paid $375,000 for each episode of the show.
12. Trump has been sued 3,500 times by his business partners, contractors, clients, employees, and banks.
13. Trump’s hair is real. He gets his haircuts from his wife Melania.
14. Donald Trump is of German and Scottish ancestry.
15. His family’s name was originally Drumpf or Drumpft but changed to Trump when the Thirty Years’ War occurred in the 1600s.
16. As of 2017, at least 24 women have accused Donald Trump of inappropriate sexual behavior in several incidents over the last 30 years.
17. 17. Trump’s family fortune began when his grandfather Frederick Trump pulled in a fortune by operating restaurants and boarding houses in the boom towns of Seattle and Klondike, Canada.
18. Trump attended Fordham University, Wharton School at the University of Pennsylvania and graduated Wharton in 1968 with a Bachelor of Science degree in economics.
19. Donald Trump is famously self-conscious about the length of his fingers.
20. 20. He once ran the Donald J. Trump Foundation established in 1988, but was shut down by the NY State Attorney General’s office in 2013 for multiple violations.
21. Donald Trump owns and operates around 18 golf courses around the world.
22. Trump was a registered Democrat between 2001 and 2009.
